### ISSUE TITLE
Potential enhancement: cache parameters in localStorage

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [codeAdrian/modern-fluid-typography-editor#6]
It may be useful to cache a user's parameters in `localStorage` and load them the next time they return to the app. A reset button could also be added somewhere in the UI to reset to the defaults. What are your thoughts on this? And if you think it's worth adding to the app, would you be open to me putting in a PR?

**Comment by codeAdrian** [comment]
Hi @AleksandrHovhannisyan ,
thanks for the suggestions.

I've released update just yesterday where parameters can be stored in a URL and copied, so they can easily return to the specific config if they wish to do so.

As for the reset to defaults, I don't think that it will be useful since there are no "defaults" to speak of. Default is determined by the root font size in the design and everything else is configurable. I've set these starting values to quickly onboard users and show them how the app works. I would like to stick to a minimum amount of form inputs and buttons.

However, I'm thinking about adding an alternate input mode that can be toggled, where users can input 2 screen width values - one for where the fluid behavior starts and other for the end, so the two dynamic values (relative size and viewport rate) are calculated.

Let me know what you think

**Comment by AleksandrHovhannisyan** [comment]
Oh nice, URL params sound like the better way to go for sure!

Sorry, by defaults, I just meant the default parameters presented by the app. But this isn't relevant with your approach, imo.

Two widths might be useful, yeah 👍
